# create a simple action to print "Hello, World!" in the logs.
name: 'My Composite Action'
description: 'Prints message from Bash' 

runs:
  using: 'composite'
  steps:
    - name: Print Message
      shell: bash
      run: echo "Hello from Gemma!"