# create a simple action to print "Hello, World!" in the logs.
name: 'My Composite Action'
description: 'Prints message from Bash' 

runs:
  using: 'composite'
  steps:
    - name: Print Message
      uses: actions/github-checkout@v2
    - name: Run python tests
      run: python -m unittest discover -s tests