name: Exercise - Simple Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  add-5-3:
    uses: ./.github/workflows/reusable-simple.yaml
    with:
      num1: 5
      num2: 3

  add-10-20:
    uses: ./.github/workflows/reusable-simple.yaml
    with:
      num1: 10
      num2: 20

  show-results:
    needs: [add-5-3, add-10-20]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "5 + 3 = ${{ needs.add-5-3.outputs.sum }}"
          echo "10 + 20 = ${{ needs.add-10-20.outputs.sum }}"
