name: Resuable Workflow
on: workflow_call

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: print a message
          uses: actions/checkout@v2
        - name: Run shell tests
          shell: bash
          run: echo "Hello from Gemma!"
