name: Resuable Workflow
on: workflow_call

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: print a message
          uses: actions/github-checkout@v4
        - name: Run python tests
          shell: bash
          run: echo "Hello from Gemma!"
